/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sachintha
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outerPanel = new java.awt.Panel();
        Home1 = new java.awt.Panel();
        Page_Title = new javax.swing.JLabel();
        TransparentBoxSmall4 = new javax.swing.JLabel();
        s_icon4 = new javax.swing.JLabel();
        black_pane_top = new javax.swing.JLabel();
        white_transparent_panel_title = new javax.swing.JLabel();
        black_pane_bottom = new javax.swing.JLabel();
        ico_title = new javax.swing.JLabel();
        background_img = new javax.swing.JLabel();
        TransparentBoxSmall34 = new javax.swing.JLabel();
        Home2 = new java.awt.Panel();
        Page_Title1 = new javax.swing.JLabel();
        TransparentBoxSmall5 = new javax.swing.JLabel();
        s_icon5 = new javax.swing.JLabel();
        black_pane_top1 = new javax.swing.JLabel();
        white_transparent_panel_title1 = new javax.swing.JLabel();
        black_pane_bottom1 = new javax.swing.JLabel();
        ico_title1 = new javax.swing.JLabel();
        background_img1 = new javax.swing.JLabel();
        TransparentBoxSmall35 = new javax.swing.JLabel();
        Home3 = new java.awt.Panel();
        Page_Title2 = new javax.swing.JLabel();
        TransparentBoxSmall6 = new javax.swing.JLabel();
        s_icon6 = new javax.swing.JLabel();
        black_pane_top2 = new javax.swing.JLabel();
        white_transparent_panel_title2 = new javax.swing.JLabel();
        black_pane_bottom2 = new javax.swing.JLabel();
        ico_title2 = new javax.swing.JLabel();
        background_img2 = new javax.swing.JLabel();
        TransparentBoxSmall36 = new javax.swing.JLabel();
        s_icon = new javax.swing.JLabel();
        s_icon1 = new javax.swing.JLabel();
        main_title = new javax.swing.JLabel();
        sideBlack2 = new javax.swing.JLabel();
        s_icon3 = new javax.swing.JLabel();
        sideBlack = new javax.swing.JLabel();
        sideBlack1 = new javax.swing.JLabel();
        img_black2 = new javax.swing.JLabel();
        Backgroud_iamge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(325, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        outerPanel.setLayout(new java.awt.CardLayout());

        Home1.setLayout(null);

        Page_Title.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title.setForeground(java.awt.Color.white);
        Page_Title.setText("Home");
        Home1.add(Page_Title);
        Page_Title.setBounds(40, 0, 140, 21);

        TransparentBoxSmall4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/back02.png"))); // NOI18N
        TransparentBoxSmall4.setText("larasparet");
        TransparentBoxSmall4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransparentBoxSmall4MouseClicked(evt);
            }
        });
        Home1.add(TransparentBoxSmall4);
        TransparentBoxSmall4.setBounds(-320, 0, 710, 20);

        s_icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/Icon-Small_home.png"))); // NOI18N
        s_icon4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s_icon4MouseClicked(evt);
            }
        });
        Home1.add(s_icon4);
        s_icon4.setBounds(10, 0, 30, 40);

        black_pane_top.setBackground(new java.awt.Color(255, 255, 255));
        black_pane_top.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        black_pane_top.setForeground(new java.awt.Color(255, 255, 255));
        black_pane_top.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/ash.png"))); // NOI18N
        black_pane_top.setText("User ID:");
        Home1.add(black_pane_top);
        black_pane_top.setBounds(0, 0, 310, 300);

        white_transparent_panel_title.setText("larasparet");
        white_transparent_panel_title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                white_transparent_panel_titleMouseClicked(evt);
            }
        });
        Home1.add(white_transparent_panel_title);
        white_transparent_panel_title.setBounds(-320, 0, 710, 20);

        black_pane_bottom.setBackground(new java.awt.Color(255, 255, 255));
        black_pane_bottom.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        black_pane_bottom.setForeground(new java.awt.Color(255, 255, 255));
        black_pane_bottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/ash.png"))); // NOI18N
        black_pane_bottom.setText("User ID:");
        Home1.add(black_pane_bottom);
        black_pane_bottom.setBounds(0, 300, 310, 200);

        ico_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2013-06-13-13.13.33.png"))); // NOI18N
        Home1.add(ico_title);
        ico_title.setBounds(-290, -370, 600, 920);

        background_img.setText("larasparet");
        Home1.add(background_img);
        background_img.setBounds(-320, -570, 670, 1160);

        TransparentBoxSmall34.setText("larasparet");
        Home1.add(TransparentBoxSmall34);
        TransparentBoxSmall34.setBounds(-320, -570, 670, 1160);

        outerPanel.add(Home1, "card4");

        Home2.setLayout(null);

        Page_Title1.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title1.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title1.setForeground(java.awt.Color.white);
        Page_Title1.setText("Home2");
        Home2.add(Page_Title1);
        Page_Title1.setBounds(40, 0, 140, 21);

        TransparentBoxSmall5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/back02.png"))); // NOI18N
        TransparentBoxSmall5.setText("larasparet");
        TransparentBoxSmall5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransparentBoxSmall5MouseClicked(evt);
            }
        });
        Home2.add(TransparentBoxSmall5);
        TransparentBoxSmall5.setBounds(-320, 0, 710, 20);

        s_icon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/Icon-Small_map.png"))); // NOI18N
        s_icon5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s_icon5MouseClicked(evt);
            }
        });
        Home2.add(s_icon5);
        s_icon5.setBounds(10, 0, 30, 40);

        black_pane_top1.setBackground(new java.awt.Color(255, 255, 255));
        black_pane_top1.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        black_pane_top1.setForeground(new java.awt.Color(255, 255, 255));
        black_pane_top1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/ash.png"))); // NOI18N
        black_pane_top1.setText("User ID:");
        Home2.add(black_pane_top1);
        black_pane_top1.setBounds(0, 0, 310, 300);

        white_transparent_panel_title1.setText("larasparet");
        white_transparent_panel_title1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                white_transparent_panel_title1MouseClicked(evt);
            }
        });
        Home2.add(white_transparent_panel_title1);
        white_transparent_panel_title1.setBounds(-320, 0, 710, 20);

        black_pane_bottom1.setBackground(new java.awt.Color(255, 255, 255));
        black_pane_bottom1.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        black_pane_bottom1.setForeground(new java.awt.Color(255, 255, 255));
        black_pane_bottom1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/ash.png"))); // NOI18N
        black_pane_bottom1.setText("User ID:");
        Home2.add(black_pane_bottom1);
        black_pane_bottom1.setBounds(0, 300, 310, 200);

        ico_title1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2013-06-13-13.13.33.png"))); // NOI18N
        Home2.add(ico_title1);
        ico_title1.setBounds(-290, -370, 600, 920);

        background_img1.setText("larasparet");
        Home2.add(background_img1);
        background_img1.setBounds(-320, -570, 670, 1160);

        TransparentBoxSmall35.setText("larasparet");
        Home2.add(TransparentBoxSmall35);
        TransparentBoxSmall35.setBounds(-320, -570, 670, 1160);

        outerPanel.add(Home2, "card4");

        Home3.setLayout(null);

        Page_Title2.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title2.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title2.setForeground(java.awt.Color.white);
        Page_Title2.setText("Home3");
        Home3.add(Page_Title2);
        Page_Title2.setBounds(40, 0, 140, 21);

        TransparentBoxSmall6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/back02.png"))); // NOI18N
        TransparentBoxSmall6.setText("larasparet");
        TransparentBoxSmall6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransparentBoxSmall6MouseClicked(evt);
            }
        });
        Home3.add(TransparentBoxSmall6);
        TransparentBoxSmall6.setBounds(-320, 0, 710, 20);

        s_icon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/Icon-Small.png"))); // NOI18N
        s_icon6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s_icon6MouseClicked(evt);
            }
        });
        Home3.add(s_icon6);
        s_icon6.setBounds(10, 0, 30, 40);

        black_pane_top2.setBackground(new java.awt.Color(255, 255, 255));
        black_pane_top2.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        black_pane_top2.setForeground(new java.awt.Color(255, 255, 255));
        black_pane_top2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/ash.png"))); // NOI18N
        black_pane_top2.setText("User ID:");
        Home3.add(black_pane_top2);
        black_pane_top2.setBounds(0, 0, 310, 300);

        white_transparent_panel_title2.setText("larasparet");
        white_transparent_panel_title2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                white_transparent_panel_title2MouseClicked(evt);
            }
        });
        Home3.add(white_transparent_panel_title2);
        white_transparent_panel_title2.setBounds(-320, 0, 710, 20);

        black_pane_bottom2.setBackground(new java.awt.Color(255, 255, 255));
        black_pane_bottom2.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        black_pane_bottom2.setForeground(new java.awt.Color(255, 255, 255));
        black_pane_bottom2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/ash.png"))); // NOI18N
        black_pane_bottom2.setText("User ID:");
        Home3.add(black_pane_bottom2);
        black_pane_bottom2.setBounds(0, 300, 310, 200);

        ico_title2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2013-06-13-13.13.33.png"))); // NOI18N
        Home3.add(ico_title2);
        ico_title2.setBounds(-290, -370, 600, 920);

        background_img2.setText("larasparet");
        Home3.add(background_img2);
        background_img2.setBounds(-320, -570, 670, 1160);

        TransparentBoxSmall36.setText("larasparet");
        Home3.add(TransparentBoxSmall36);
        TransparentBoxSmall36.setBounds(-320, -570, 670, 1160);

        outerPanel.add(Home3, "card4");

        getContentPane().add(outerPanel);
        outerPanel.setBounds(30, 30, 320, 500);

        s_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/Icon-Small_map.png"))); // NOI18N
        s_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s_iconMouseClicked(evt);
            }
        });
        getContentPane().add(s_icon);
        s_icon.setBounds(0, 100, 30, 40);

        s_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/Icon-Small.png"))); // NOI18N
        s_icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s_icon1MouseClicked(evt);
            }
        });
        getContentPane().add(s_icon1);
        s_icon1.setBounds(0, 140, 30, 40);

        main_title.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        main_title.setForeground(java.awt.Color.white);
        main_title.setText("Lydia v 2.0");
        getContentPane().add(main_title);
        main_title.setBounds(40, 0, 150, 22);

        sideBlack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/28h3fwh.png"))); // NOI18N
        sideBlack2.setText("jLabel2");
        getContentPane().add(sideBlack2);
        sideBlack2.setBounds(-120, 0, 480, 30);

        s_icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/Icon-Small_home.png"))); // NOI18N
        s_icon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s_icon3MouseClicked(evt);
            }
        });
        getContentPane().add(s_icon3);
        s_icon3.setBounds(0, 60, 30, 40);

        sideBlack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/28h3fwh.png"))); // NOI18N
        sideBlack.setText("jLabel2");
        getContentPane().add(sideBlack);
        sideBlack.setBounds(-100, 0, 130, 550);

        sideBlack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/28h3fwh.png"))); // NOI18N
        sideBlack1.setText("jLabel2");
        getContentPane().add(sideBlack1);
        sideBlack1.setBounds(-100, 0, 480, 550);

        img_black2.setBackground(new java.awt.Color(255, 255, 255));
        img_black2.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        img_black2.setForeground(new java.awt.Color(255, 255, 255));
        img_black2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interf/ash.png"))); // NOI18N
        getContentPane().add(img_black2);
        img_black2.setBounds(-80, 0, 470, 30);

        Backgroud_iamge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2013-06-13-13.13.33.png"))); // NOI18N
        getContentPane().add(Backgroud_iamge);
        Backgroud_iamge.setBounds(-220, -460, 670, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_iconMouseClicked
        // removing pane
        outerPanel.removeAll();
        outerPanel.repaint();
        outerPanel.revalidate();
        //adding pane
        outerPanel.add(Home2);
        outerPanel.repaint();
        outerPanel.revalidate();
        
    }//GEN-LAST:event_s_iconMouseClicked

    private void s_icon3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_icon3MouseClicked
          // removing pane
        outerPanel.removeAll();
        outerPanel.repaint();
        outerPanel.revalidate();
        //adding pane
        outerPanel.add(Home1);
        outerPanel.repaint();
        outerPanel.revalidate();
        
    }//GEN-LAST:event_s_icon3MouseClicked

    private void white_transparent_panel_titleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_white_transparent_panel_titleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_white_transparent_panel_titleMouseClicked

    private void TransparentBoxSmall4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransparentBoxSmall4MouseClicked
       
    }//GEN-LAST:event_TransparentBoxSmall4MouseClicked

    private void s_icon4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_icon4MouseClicked
  
    }//GEN-LAST:event_s_icon4MouseClicked

    private void s_icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_icon1MouseClicked
         // removing pane
        outerPanel.removeAll();
        outerPanel.repaint();
        outerPanel.revalidate();
         //adding pane
        outerPanel.add(Home3);
        outerPanel.repaint();
        outerPanel.revalidate();
    }//GEN-LAST:event_s_icon1MouseClicked

    private void TransparentBoxSmall5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransparentBoxSmall5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TransparentBoxSmall5MouseClicked

    private void s_icon5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_icon5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_s_icon5MouseClicked

    private void white_transparent_panel_title1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_white_transparent_panel_title1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_white_transparent_panel_title1MouseClicked

    private void TransparentBoxSmall6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransparentBoxSmall6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TransparentBoxSmall6MouseClicked

    private void s_icon6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_icon6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_s_icon6MouseClicked

    private void white_transparent_panel_title2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_white_transparent_panel_title2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_white_transparent_panel_title2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroud_iamge;
    private java.awt.Panel Home1;
    private java.awt.Panel Home2;
    private java.awt.Panel Home3;
    private javax.swing.JLabel Page_Title;
    private javax.swing.JLabel Page_Title1;
    private javax.swing.JLabel Page_Title2;
    private javax.swing.JLabel TransparentBoxSmall34;
    private javax.swing.JLabel TransparentBoxSmall35;
    private javax.swing.JLabel TransparentBoxSmall36;
    private javax.swing.JLabel TransparentBoxSmall4;
    private javax.swing.JLabel TransparentBoxSmall5;
    private javax.swing.JLabel TransparentBoxSmall6;
    private javax.swing.JLabel background_img;
    private javax.swing.JLabel background_img1;
    private javax.swing.JLabel background_img2;
    private javax.swing.JLabel black_pane_bottom;
    private javax.swing.JLabel black_pane_bottom1;
    private javax.swing.JLabel black_pane_bottom2;
    private javax.swing.JLabel black_pane_top;
    private javax.swing.JLabel black_pane_top1;
    private javax.swing.JLabel black_pane_top2;
    private javax.swing.JLabel ico_title;
    private javax.swing.JLabel ico_title1;
    private javax.swing.JLabel ico_title2;
    private javax.swing.JLabel img_black2;
    private javax.swing.JLabel main_title;
    private java.awt.Panel outerPanel;
    private javax.swing.JLabel s_icon;
    private javax.swing.JLabel s_icon1;
    private javax.swing.JLabel s_icon3;
    private javax.swing.JLabel s_icon4;
    private javax.swing.JLabel s_icon5;
    private javax.swing.JLabel s_icon6;
    private javax.swing.JLabel sideBlack;
    private javax.swing.JLabel sideBlack1;
    private javax.swing.JLabel sideBlack2;
    private javax.swing.JLabel white_transparent_panel_title;
    private javax.swing.JLabel white_transparent_panel_title1;
    private javax.swing.JLabel white_transparent_panel_title2;
    // End of variables declaration//GEN-END:variables
}
